name: Main branch coverage

on:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  backend-unit-tests-coverage:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Unit tests
        run: |
          env CGO_ENABLED=0 go test -v ./... -coverprofile coverage.out -coverpkg=./... -covermode atomic

      - uses: codecov/codecov-action@v3
        if: always()
        with:
          fail_ci_if_error: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-coverage
          path: coverage.out
          if-no-files-found: error
          retention-days: 30
