name: Release

on: push

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/goreleaser.yaml@v1.0.20
    with:
      beta: ${{ github.ref_name == 'main' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
